# Generated by Django 5.2.3 on 2025-07-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recepi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepi_name', models.CharField(max_length=100)),
                ('recepi_description', models.TextField()),
                ('recepi_image', models.ImageField(upload_to='recepi')),
            ],
        ),
    ]
